### ISSUE TITLE
State transition does not appear to be thread-safe

### ISSUE THREAD

**Issue by skatenerd** [gocardless/statesman#201] opened 2016-01-26 19:51 UTC
I just started using Statesman, and I think it's great.  So, first off, thank you for your hard work :-)

When I have multiple threads transitioning the same (ActveRecord) model, sometimes I cause a `TransitionConflictError` (with an underlying Postgres error `PG::UniqueViolation`).

I believe this is because of the way we populate the `sort_by` field on update.  We seem to [compute the next sort_key](https://github.com/gocardless/statesman/blob/master/lib/statesman/adapters/active_record.rb#L66) before entering the DB transaction.  I would imagine that it's possible for multiple threads to simultaneously compute the "new" `sort_key`, and for both of them to try to write the same key to the DB.

Perhaps we could push the key-increment logic down into the DB transaction?

**Comment by hale** [comment] 2016-01-27 01:44
This can be used as a workaround in the meantime: https://github.com/gocardless/statesman/blob/140a18115fbe12609624383a5908e869ad966dcd/README.md#machineretry_conflicts

```ruby
def transition_to(state, metadata = {})
  Statesman::Machine.retry_conflicts(3) do
    super(state, metadata)
  end
end
```

**Comment by skatenerd** [comment] 2016-01-27 02:51
Thanks

**Comment by isaacseymour** [comment] 2016-01-27 09:26
Pushing the key increment into the DB transaction would break the guarantees around the ordering of transitions. For example, let's say we have a state machine which starts in pending and can transition to either passed or failed, and two threads (or processes) which read an instance of this model as being "pending" and independently decide to transition it to passed and failed. Both think this is a valid transition, so attempt to write sort_key 10. The uniqueness guarantee on `(parent_id, sort_key)` catches the conflict, so only one succeeds. However, if the increment was pushed down into the database, you'd end up with a transition history of either "pending -> passed -> failed" or "pending -> failed -> passed", neither of which is valid! `retry_conflicts` will retry the entire transition (i.e. reload the current state of the model and re-run the block it is passed).

In this simple case that's not much use, but if you have a model which transitions through several states, but can be "cancelled" at any point (say, a shopping order), retrying conflicts when cancelling it would be very useful - you don't much care if it goes from "reserving stock" to "preparing box" in the mean time, it should be cancelled either way!

I hope that makes sense? If it's clearer, I can write up some code to demonstrate this when I'm back at a real keyboard if that would help.

**Comment by skatenerd** [comment] 2016-01-27 17:43
This makes sense.  It sounds like the real underlying problem is that the state can change between when you examine it and when your update gets executed.

It almost sounds like we want to do everything (examine the state, decide to change it, actually change it) all with some sort of row-level lock.

**Comment by isaacseymour** [comment] 2016-01-27 21:17
Yep, I think that would work, but might have some pretty bad performance implications. To implement it in Statesman we'd need to reload the model with a `SELECT FOR UPDATE` (I think?) just after opening the transaction for the transition - that would mean hitting the database twice rather than once, which might have a significant impact if you're doing a lot of transitions!

The current solution of just raising and rolling back on conflicts isn't so bad I don't think, especially with `retry_conflicts` as an option.

**Comment by greysteil** [comment] 2016-02-28 18:11
Closing, unless anyone feels strongly. Bouncing off the database is the intended way to deal with races here, and `retry_conflicts` makes doing the right thing when a race is detected relatively easy.

**Closed by greysteil** 2016-02-28 18:11 UTC

**Comment by tholder** [comment] 2016-06-17 10:15
For anyone that has a similar problem, I can confirm that this happens. The problem presented itself to me because of performing a Sidekiq job that happens within a state transition, the sidekiq job performs another state tansition.

I wasn't quite clear how retry conflicts works, so I ended up putting in a model concern such as:

```ruby
module StatesmanRetry

    def transition_to(state, metadata = {})
      Statesman::Machine.retry_conflicts(3) do
        super(state, metadata)
      end
    end

end
```

And, then include in my statemachine like:

```ruby
class MyStateMachine
  include Statesman::Machine
  include StatesmanRetry
```

**Comment by erose** [comment] 2017-04-30 19:11
I've been seeing this problem as well.
