### ISSUE TITLE
in_state is not worked in rails 5

### ISSUE THREAD

**Issue by zw963** [gocardless/statesman#224] opened 2016-08-20 10:06 UTC
``` rb
NoMethodError: undefined method `table_name' for nil:NilClass
from /home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/statesman-2.0.1/lib/statesman/adapters/active_record_queries.rb:49:in `model_table'
```

Following is backtrace:

``` rb
["/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/statesman-2.0.1/lib/statesman/adapters/active_record_queries.rb:49:in `model_table'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/statesman-2.0.1/lib/statesman/adapters/active_record_queries.rb:53:in `most_recent_transition_join'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/statesman-2.0.1/lib/statesman/adapters/active_record_queries.rb:12:in `in_state'",
 "(pry):1:in `<main>'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `call'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/pry-nav-0.2.4/lib/pry-nav/pry_ext.rb:17:in `start_with_pry_nav'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/commands/console.rb:65:in `start'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/commands/console_helper.rb:9:in `start'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:78:in `console'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/commands/commands_tasks.rb:49:in `run_command!'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/railties-5.0.0/lib/rails/commands.rb:18:in `<top (required)>'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `block in require'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:293:in `require'",
 "/home/zw963/Xthink/ershou_web/bin/rails:9:in `<top (required)>'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `block in load'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:259:in `load_dependency'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/activesupport-5.0.0/lib/active_support/dependencies.rb:287:in `load'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/commands/rails.rb:6:in `call'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/command_wrapper.rb:38:in `call'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/application.rb:191:in `block in serve'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/application.rb:161:in `fork'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/application.rb:161:in `serve'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/application.rb:131:in `block in run'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/application.rb:125:in `loop'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/application.rb:125:in `run'",
 "/home/zw963/.rvm/gems/ruby-2.2.4@ershou_web/gems/spring-1.7.2/lib/spring/application/boot.rb:19:in `<top (required)>'",
 "/home/zw963/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
 "/home/zw963/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'",
 "-e:1:in `<main>'"]
```

**Comment by zw963** [comment] 2016-08-27 02:41
This problem is same as #220.

**Comment by zw963** [comment] 2016-11-15 10:52
Seem like no one care about this issue ...

Reopen  ....

**Comment by hmac** [comment] 2017-02-21 18:36
I think you're right that this is a duplicate of #220. Going to close this to reduce noise.

Hopefully we can merge https://github.com/gocardless/statesman/pull/221 soon to fix this.

**Closed by hmac** 2017-02-21 18:36 UTC
